//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arenda
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public House()
        {
            this.Contract = new HashSet<Contract>();
        }
    
        public int IdObject { get; set; }
        public decimal Cost { get; set; }
        public System.DateTime DateOfCreation { get; set; }
        public string Description { get; set; }
        public string ObjectArea { get; set; }
        public int IdAddress { get; set; }
        public int IdType { get; set; }
        public int Rooms { get; set; }
        public string Status { get; set; }
    
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contract { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual TypeObject TypeObject { get; set; }
    }
}
