//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arenda
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArendaEntities : DbContext
    {
        public ArendaEntities()
            : base("name=ArendaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Agent> Agent { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<Contragent> Contragent { get; set; }
        public virtual DbSet<Object> Object { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<TContract> TContract { get; set; }
        public virtual DbSet<TypeObject> TypeObject { get; set; }
    }
}
